CFLAGS= -g3 -I . -lSDL2 -lSDL2main -lSDL2_image -lSDL2_image -lSDL2_ttf -lm -Iduktape/src/

SOURCES=src/*.c \
 	src/browser/*.c \
 	src/browser/classes/*.c \
 	src/adapters/*.c \
  	src/rendering/*.c \
	src/cache/*.c \
	src/exploits/*.c \
   	duktape/src/duktape.c \
   	duktape/extras/console/duk_console.c \
#	tinypy/modules/math/*.c \
#	tinypy/modules/random/*.c \

default: js all

js:
	cat js_src/*.js > quark.js

all: js
	gcc ${SOURCES} ${CFLAGS} liblexbor.so -o quark
