FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

ENV VITASDK=/usr/local/vitasdk
ENV PATH=${PATH}:${VITASDK}/bin

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get install emacs-nox -y

RUN apt-get install zip tar curl cmake build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl1.2-dev git-core -y

RUN apt-get install -y wget xz-utils python3 apt-transport-https ca-certificates gnupg software-properties-common bzip2 sudo

# X11 + VNC Server Setup
RUN apt-get install -y xorg i3 tigervnc-standalone-server

RUN \
    git clone https://github.com/vitasdk/vdpm && \
    cd vdpm && \
    ./bootstrap-vitasdk.sh && \
    ./install-all.sh

WORKDIR /quark

COPY . .

RUN /quark/scripts/setup.sh && cp /quark/liblexbor.so /lib/liblexbor.so.2

# Requirements for Vita3K
RUN apt-get install -y qt6-base-dev libqt6svg6-dev qt6-base-private-dev pulseaudio p7zip

RUN wget https://github.com/Vita3K/Vita3K-builds/releases/download/3773/vita3k-3773-9226cb52_ubuntu.7z && 7z x -o/quark/ vita3k-3773-9226cb52_ubuntu.7z && chmod +x /quark/vita3k-9226cb52-zip-ubuntu-22.04/Vita3K && ln -s /quark/vita3k-9226cb52-zip-ubuntu-22.04/Vita3K /usr/bin/Vita3K

RUN chmod +x /quark/scripts/run_emulator.sh && mkdir -p /root/.config/i3 && cp /quark/scripts/i3config /root/.config/i3/config

RUN apt-get install -y xterm

ENTRYPOINT [ "bash", "/quark/scripts/i3_entrypoint.sh" ]
